#!/bin/bash

set -e 

###########################
# Gather configuration
###########################

AUTO_ACCEPT=${AUTO_ACCEPT:-False}
CYTHON_ENABLE=${CYTHON_ENABLE:-False}
ENABLE_GPU_GRAINS=${ENABLE_GPU_GRAINS:-False}
EXTERNAL_NODES=${EXTERNAL_NODES:-None}
FAILHARD=${FAILHARD:-False}
FILESERVER_EVENTS=${FILESERVER_EVENTS:-False}
FILESERVER_FOLLOWSYMLINKS=${FILESERVER_FOLLOWSYMLINKS:-False}
FILESERVER_IGNORESYMLINKS=${FILESERVER_IGNORESYMLINKS:-False}
FILESERVER_LIMIT_TRAVERSAL=${FILESERVER_LIMIT_TRAVERSAL:-False}
FILE_BUFFER_SIZE=${FILE_BUFFER_SIZE:-1048576}
FILE_RECV=${FILE_RECV:-False}
FILE_RECV_MAX_SIZE=${FILE_RECV_MAX_SIZE:-100}
GITFS_SSL_VERIFY=${GITFS_SSL_VERIFY:-True}
HASH_TYPE=${HASH_TYPE:-md5}
IPV6=${IPV6:-False}
JINJA_LSTRIP_BLOCKS=${JINJA_LSTRIP_BLOCKS:-False}
JINJA_TRIM_BLOCKS=${JINJA_TRIM_BLOCKS:-False}
JOB_CACHE=${JOB_CACHE:-True}
KEEP_JOBS=${KEEP_JOBS:-24}
LOG_LEVEL=${LOG_LEVEL:-warning}
LOOP_INTERVAL=${LOOP_INTERVAL:-60}
MASTER_TOPS=${MASTER_TOPS:-{}}
MAX_OPEN_FILES=${MAX_OPEN_FILES:-100000}
MINION_DATA_CACHE=${MINION_DATA_CACHE:-True}
OPEN_MODE=${OPEN_MODE:-False}
ORDER_MASTERS=${ORDER_MASTERS:-False}
OUTPUT=${OUTPUT:-nested}
PERMISSIVE_PKI_ACCESS=${PERMISSIVE_PKI_ACCESS:-False}
PILLAR_GITFS_SSL_VERIFY=${PILLAR_GITFS_SSL_VERIFY:-True}
PILLAR_OPTS=${PILLAR_OPTS:-True}
RANGE_SERVER=${RANGE_SERVER:-}
RENDERER=${RENDERER:-yaml_jinja}
RUNNER_DIRS=${RUNNER_DIRS:-[]}
SIGN_PUB_MESSAGES=${SIGN_PUB_MESSAGES:-False}
STATE_OUTPUT=${STATE_OUTPUT:-full}
STATE_TOP=${STATE_TOP:-top.sls}
STATE_VERBOSE=${STATE_VERBOSE:-True}
TIMEOUT=${TIMEOUT:-5}
TOKEN_EXPIRE=${TOKEN_EXPIRE:-43200}
WORKER_THREADS=${WORKER_THREADS:-5}


####################
# Configure app
####################

cp /app/master-configurable.conf.template \
    /etc/salt/master.d/master-configurable.conf

sed 's/{{AUTO_ACCEPT}}/'"${AUTO_ACCEPT}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{CYTHON_ENABLE}}/'"${CYTHON_ENABLE}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{ENABLE_GPU_GRAINS}}/'"${ENABLE_GPU_GRAINS}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{EXTERNAL_NODES}}/'"${EXTERNAL_NODES}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{FAILHARD}}/'"${FAILHARD}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{FILESERVER_EVENTS}}/'"${FILESERVER_EVENTS}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{FILESERVER_FOLLOWSYMLINKS}}/'"${FILESERVER_FOLLOWSYMLINKS}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{FILESERVER_IGNORESYMLINKS}}/'"${FILESERVER_IGNORESYMLINKS}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{FILESERVER_LIMIT_TRAVERSAL}}/'"${FILESERVER_LIMIT_TRAVERSAL}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{FILE_BUFFER_SIZE}}/'"${FILE_BUFFER_SIZE}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{FILE_RECV}}/'"${FILE_RECV}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{FILE_RECV_MAX_SIZE}}/'"${FILE_RECV_MAX_SIZE}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{GITFS_SSL_VERIFY}}/'"${GITFS_SSL_VERIFY}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{HASH_TYPE}}/'"${HASH_TYPE}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{IPV6}}/'"${IPV6}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{JINJA_LSTRIP_BLOCKS}}/'"${JINJA_LSTRIP_BLOCKS}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{JINJA_TRIM_BLOCKS}}/'"${JINJA_TRIM_BLOCKS}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{JOB_CACHE}}/'"${JOB_CACHE}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{KEEP_JOBS}}/'"${KEEP_JOBS}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{LOG_LEVEL}}/'"${LOG_LEVEL}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{LOOP_INTERVAL}}/'"${LOOP_INTERVAL}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{MASTER_TOPS}}/'"${MASTER_TOPS}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{MAX_OPEN_FILES}}/'"${MAX_OPEN_FILES}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{MINION_DATA_CACHE}}/'"${MINION_DATA_CACHE}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{OPEN_MODE}}/'"${OPEN_MODE}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{ORDER_MASTERS}}/'"${ORDER_MASTERS}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{OUTPUT}}/'"${OUTPUT}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{PERMISSIVE_PKI_ACCESS}}/'"${PERMISSIVE_PKI_ACCESS}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{PILLAR_GITFS_SSL_VERIFY}}/'"${PILLAR_GITFS_SSL_VERIFY}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{PILLAR_OPTS}}/'"${PILLAR_OPTS}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{RANGE_SERVER}}/'"${RANGE_SERVER}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{RENDERER}}/'"${RENDERER}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{RUNNER_DIRS}}/'"${RUNNER_DIRS}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{SIGN_PUB_MESSAGES}}/'"${SIGN_PUB_MESSAGES}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{STATE_OUTPUT}}/'"${STATE_OUTPUT}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{STATE_TOP}}/'"${STATE_TOP}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{STATE_VERBOSE}}/'"${STATE_VERBOSE}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{TIMEOUT}}/'"${TIMEOUT}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{TOKEN_EXPIRE}}/'"${TOKEN_EXPIRE}"'/' \
    -i /etc/salt/master.d/master-configurable.conf

sed 's/{{WORKER_THREADS}}/'"${WORKER_THREADS}"'/' \
    -i /etc/salt/master.d/master-configurable.conf


##############
# Run app
##############

salt-master
